FROM openjdk:17-oracle

COPY subscriber-app-0.0.1-SNAPSHOT.jar subscriber-app-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","subscriber-app-0.0.1-SNAPSHOT.jar"]

#docker login
#docker build -t anarchtsu/subscriber-app .
#docker push anarchtsu/subscriber-app