FROM openjdk:17-oracle

COPY publisher-app-0.0.1-SNAPSHOT.jar publisher-app-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","publisher-app-0.0.1-SNAPSHOT.jar"]

#docker login
#docker build -t anarchtsu/publisher-app .
#docker push anarchtsu/publisher-app